# Generated by Django 3.1.2 on 2021-05-29 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_auto_20210529_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_type', models.CharField(max_length=50)),
                ('d_price', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='p_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.payment'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default=1, max_length=50, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='order',
            name='d_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.delivery'),
        ),
    ]
