# Generated by Django 3.1.2 on 2021-05-21 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210521_1718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
    ]
