# Generated by Django 3.1.2 on 2021-05-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210521_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(help_text='Код поставщика', primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('city', models.CharField(db_index=True, max_length=200)),
                ('adress', models.CharField(db_index=True, max_length=200)),
                ('phone', models.CharField(db_index=True, max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'ordering': ('name',),
            },
        ),
    ]
