# Generated by Django 3.1.2 on 2021-05-25 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='adress',
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
