# Generated by Django 3.1.2 on 2021-05-23 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210523_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('d_id', models.AutoField(help_text='Код доставки', primary_key=True, serialize=False)),
                ('d_type', models.CharField(max_length=50)),
                ('d_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
