# Generated by Django 3.1.2 on 2021-05-23 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210523_1250'),
    ]



