# Generated by Django 3.1.2 on 2021-05-23 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20210523_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='d_id',
            field=models.ForeignKey(default=False, help_text='Код доставки', on_delete=django.db.models.deletion.CASCADE, to='orders.delivery'),
        ),
    ]
