# Generated by Django 3.1.2 on 2021-05-23 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20210523_1252'),
    ]


