# Generated by Django 3.1.2 on 2021-05-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_order_d_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('p_id', models.AutoField(default=1, help_text='Код доставки', primary_key=True, serialize=False)),
                ('p_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='id',
        ),
        migrations.AddField(
            model_name='order',
            name='o_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='oi_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='d_id',
            field=models.AutoField(default=1, help_text='Код доставки', primary_key=True, serialize=False),
        ),
    ]
