# Generated by Django 3.1.2 on 2021-05-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20210525_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='d_id',
            field=models.AutoField(help_text='Код доставки', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='o_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='p_id',
            field=models.AutoField(help_text='Код доставки', primary_key=True, serialize=False),
        ),
    ]
