# Generated by Django 3.1.2 on 2021-05-26 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_product_description'),
        ('account', '0001_initial'),
        ('orders', '0011_auto_20210525_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='first_name',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='d_id',
            field=models.ForeignKey(default='', help_text='Код доставки', on_delete=django.db.models.deletion.CASCADE, to='orders.delivery'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='p_id',
            field=models.ForeignKey(default='', help_text='Код оплаты', on_delete=django.db.models.deletion.CASCADE, to='orders.payment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='account.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='o_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='delivery',
            name='d_id',
            field=models.AutoField(default=1, help_text='Код доставки', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='p_id',
            field=models.AutoField(default=1, help_text='Код доставки', primary_key=True, serialize=False),
        ),
    ]
