# Generated by Django 3.1.2 on 2021-05-26 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20210526_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='d_id',
            field=models.AutoField(help_text='Код доставки', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='p_id',
            field=models.AutoField(help_text='Код доставки', primary_key=True, serialize=False),
        ),
    ]
