# Generated by Django 3.1.2 on 2021-05-26 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20210526_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='d_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='p_id',
        ),
    ]
