# Generated by Django 3.1.2 on 2021-05-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20210526_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='d_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='p_id',
        )
    ]
