# Generated by Django 3.1.2 on 2021-05-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20210526_1300'),
    ]

    operations = [


    ]
