# Generated by Django 3.1.2 on 2021-05-26 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20210526_1306'),
    ]

    operations = [

    ]
