# Generated by Django 3.1.2 on 2021-05-26 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_product_description'),
        ('orders', '0019_auto_20210526_1438'),
    ]

    operations = [

    ]
