# Generated by Django 3.1.2 on 2021-05-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20210526_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ord_del_time',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='', max_length=50, verbose_name='Статус'),
            preserve_default=False,
        ),
    ]
