# Generated by Django 3.1.2 on 2021-05-28 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20210528_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='position',
        ),
    ]
