# Generated by Django 3.1.2 on 2021-05-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_auto_20210528_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='position',
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
