# Generated by Django 3.1.2 on 2021-05-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_remove_order_braintree_id'),
    ]

    operations = [

    ]
