# Generated by Django 3.1.2 on 2021-05-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_auto_20210528_1737'),
    ]

    operations = [

    ]
