# Generated by Django 3.1.2 on 2021-05-28 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_auto_20210528_1740'),
    ]

    operations = [

    ]
