# Generated by Django 3.1.2 on 2021-05-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_auto_20210528_1750'),
    ]

    operations = [
        ]
