# Generated by Django 3.1.2 on 2021-05-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_auto_20210528_1754'),
    ]

    operations = [

    ]
